---
# tasks file for docker


- name: IPTables Rule
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    sysctl_set: yes
    reload: yes

- name: Add K8S configuration
  shell: "echo {{ hostvars['k8s_middle_server']['kube_config'] }} >> /home/{{ user }}/.kube/config"

- name: Point the Cluster
  shell: "kubectl config use-context kubernetes-admin@kubernetes"

      